import { Head } from '@inertiajs/react';
import { Download, Printer } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Row = { name: string; username: string; grade: string; section: string; completed: number; total: number; progress: number; submissions: number; status: string };
export default function Reports({ rows }: { rows: Row[] }) {
    const average = rows.length ? Math.round(rows.reduce((sum, r) => sum + r.progress, 0) / rows.length) : 0;
    return <><Head title="Reports" /><main className="soft-grid min-h-full p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">Class insights</Badge><h1 className="mt-3 text-3xl font-bold">Progress reports</h1><p className="mt-2 text-muted-foreground">A printable overview of completion and submission activity.</p></div><div className="flex gap-2 print:hidden"><Button variant="outline" onClick={() => window.print()}><Printer /> Print</Button><Button asChild><a href="/reports/progress.csv"><Download /> Export CSV</a></Button></div></header><section className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Class average</p><p className="mt-1 text-3xl font-bold">{average}%</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Students on track</p><p className="mt-1 text-3xl font-bold">{rows.filter(r => r.progress >= average).length}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Need support</p><p className="mt-1 text-3xl font-bold">{rows.filter(r => r.progress < average).length}</p></CardContent></Card></section><Card><CardHeader><CardTitle>Class progress</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Student</th><th>Class</th><th>Lessons</th><th>Progress</th><th>Submissions</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.username} className="border-b last:border-0"><td className="py-4"><p className="font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">@{row.username}</p></td><td>{row.grade} · {row.section}</td><td>{row.completed}/{row.total}</td><td><div className="flex items-center gap-2"><div className="h-2 w-28 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${row.progress}%` }} /></div>{row.progress}%</div></td><td>{row.submissions}</td><td><Badge variant="outline">{row.status}</Badge></td></tr>)}</tbody></table></CardContent></Card></div></main></>;
}
Reports.layout = { breadcrumbs: [{ title: 'Reports', href: '/reports' }] };
