<?php

// Each record maps to an existing lesson number, preserving lesson IDs and student progress.
$page = fn (string $title, string $body, string $bodyAttributes = ''): string => "<!DOCTYPE html>\n<html>\n<head><title>{$title}</title></head>\n<body{$bodyAttributes}>\n{$body}\n</body>\n</html>";

return [
    1 => [
        'title' => 'Basic HTML Structure, Headings, Paragraphs, Attributes, and Scrolling Text', 'level' => 'Basic',
        'objectives' => ['Build an HTML page with head, title, and body.', 'Use H1–H6 headings and paragraphs.', 'Add a body background attribute and a scrolling message.'],
        'introduction' => 'HTML gives a page its structure. The head holds its title; the body holds what visitors see.',
        'explanation' => 'A tag such as <h1> marks a heading. An attribute adds information inside an opening tag: bgcolor="lightblue" changes the body background. The historical <marquee> tag scrolls text; learn it here, but modern sites usually animate with CSS.',
        'syntax' => '<html> <head> <title>...</title> </head> <body bgcolor="lightblue"> <h1>...</h1> <p>...</p> <marquee>...</marquee> </body> </html>',
        'example_html' => $page('Our Classroom', '<h1>Our Classroom</h1><h2>Welcome</h2><p>We enjoy learning together.</p><marquee>Have a good day!</marquee>', ' bgcolor="lightyellow"'),
        'example_css' => '', 'activity' => 'Create a personal introduction page with a page title, background color, H1 and H2, two paragraphs, and one scrolling message.',
        'activity_html' => $page('Meet Alex', '<h1>Meet Alex</h1><h2>About Me</h2><p>I am a Grade 9 student.</p><p>I enjoy drawing and reading.</p><marquee>Thanks for visiting my page!</marquee>', ' bgcolor="lightblue"'),
        'activity_css' => '', 'guided_practice' => 'Change the example title and heading, then try a different bgcolor value and run the page.',
        'challenge' => 'Add an H3 heading and a third paragraph about a goal.', 'expected_result' => 'A colored introduction page with two headings, two paragraphs, and moving text.',
        'validation_rules' => ['tags' => ['html' => 1, 'head' => 1, 'title' => 1, 'body' => 1, 'h1' => 1, 'h2' => 1, 'p' => 2, 'marquee' => 1], 'attributes' => [['body', 'bgcolor']]],
        'quiz' => [
            ['Which tag holds visible page content?', ['<head>', '<body>', '<title>', '<html>'], 1, 'Visible content belongs in the body.'],
            ['Where does the browser-tab title belong?', ['<p>', '<h1>', '<title>', '<marquee>'], 2, 'The title tag sits inside head.'],
            ['Which is the largest heading by default?', ['<h1>', '<h3>', '<h5>', '<h6>'], 0, 'H1 is the highest heading level.'],
            ['What does bgcolor="lightblue" represent?', ['A tag', 'An attribute', 'A paragraph', 'A file'], 1, 'bgcolor is an attribute on an opening tag.'],
            ['Which tag makes the lesson’s scrolling text?', ['<scroll>', '<marquee>', '<move>', '<p>'], 1, 'The historical marquee tag scrolls text.'],
        ],
    ],
    2 => [
        'title' => 'Text Formatting and Paragraph Alignment', 'level' => 'Basic',
        'objectives' => ['Reuse the full HTML structure from Lesson 1.', 'Use bold, italic, line break, and horizontal rule tags.', 'Align paragraphs left, center, and right.'],
        'introduction' => 'Formatting helps readers notice important words and separates parts of a page.',
        'explanation' => '<b> and <i> change appearance; <strong> and <em> also convey importance or emphasis. <br> breaks a line and <hr> draws a separator. The align attribute sets paragraph alignment in this HTML-only level.',
        'syntax' => '<p align="center"><strong>Important text</strong></p> <hr> <br>',
        'example_html' => $page('Our Club', '<h1>Our Club</h1><hr><p align="center"><b>Welcome, members!</b></p><p align="left">We meet on Fridays.</p><p align="right"><i>See you soon.</i></p><br><p><em>Everyone is welcome.</em></p>'),
        'example_css' => '', 'activity' => 'Create an About Me page with H1, a horizontal line, at least three paragraphs aligned left, center, and right, bold text, italic text, and a line break.',
        'activity_html' => $page('About Sam', '<h1>About Sam</h1><hr><p align="center"><b>Welcome to my page!</b></p><p align="left">I am <strong>Sam</strong>, a student.</p><p align="right"><i>I love reading.</i></p><br><p><em>HTML is fun!</em></p>'),
        'activity_css' => '', 'guided_practice' => 'Try align="center" on one paragraph. Add <hr> below a heading and compare <b> with <strong>.',
        'challenge' => 'Use both <strong> and <em> in a new sentence.', 'expected_result' => 'An About Me page with three visibly different paragraph alignments and formatted text.',
        'validation_rules' => ['tags' => ['html' => 1, 'head' => 1, 'title' => 1, 'body' => 1, 'h1' => 1, 'hr' => 1, 'p' => 3, 'br' => 1], 'any_tags' => [['b', 'strong'], ['i', 'em']], 'special' => ['paragraph-alignments']],
        'quiz' => [
            ['Which tag draws a horizontal separator?', ['<br>', '<hr>', '<p>', '<strong>'], 1, 'The hr tag draws a thematic break.'],
            ['Which tag starts a new line?', ['<br>', '<b>', '<em>', '<title>'], 0, 'The br tag makes a line break.'],
            ['Which value centers a paragraph?', ['align="left"', 'align="middle"', 'align="center"', 'align="right"'], 2, 'Use center for centered alignment.'],
            ['Which tag marks strongly important text?', ['<strong>', '<i>', '<hr>', '<body>'], 0, 'Strong marks important content.'],
            ['Where should your H1 be placed?', ['Inside <head>', 'Inside <title>', 'Inside <body>', 'After </html>'], 2, 'Visible headings belong in body.'],
        ],
    ],
    3 => [
        'title' => 'Links and Images', 'level' => 'Basic',
        'objectives' => ['Create text hyperlinks using href.', 'Show images using src, alt, width, and height.', 'Make an image itself a link.'],
        'introduction' => 'Links connect pages, while images make content more visual.',
        'explanation' => 'href tells an <a> link where to go. src tells an <img> where to get its image. Alt text describes an image when it cannot load and helps screen-reader users. Width and height control display dimensions. A link can open in the same tab or, with target="_blank", a new tab.',
        'syntax' => '<a href="https://example.com">Visit</a> <img src="photo.jpg" alt="Description" width="240" height="160">',
        'example_html' => $page('Nature Club', '<h1>Nature Club</h1><p>Explore the outdoors with us.</p><a href="https://example.com">Read more</a><p><a href="https://example.com"><img src="https://placehold.co/180x110?text=Nature" alt="Nature scene" width="180" height="110"></a></p>'),
        'example_css' => '', 'activity' => 'Build My Favorite Website with a heading, description paragraph, one image, one text hyperlink, and one image hyperlink. Give every image useful alt text.',
        'activity_html' => $page('My Favorite Website', '<h1>My Favorite Website</h1><p>I like learning about space.</p><img src="https://placehold.co/240x130?text=Space" alt="Stars in space" width="240" height="130"><p><a href="https://example.com">Visit my favorite site</a></p><a href="https://example.com"><img src="https://placehold.co/150x80?text=Explore" alt="Explore link" width="150" height="80"></a>'),
        'activity_css' => '', 'guided_practice' => 'Create a text link first. Then add an image with descriptive alt text and place another image inside an <a> tag.',
        'challenge' => 'Add height to an image and explain what happens when its source is unavailable.', 'expected_result' => 'A page with visible images and both text and image links.',
        'validation_rules' => ['tags' => ['h1' => 1, 'p' => 1, 'a' => 2, 'img' => 2], 'attributes' => [['a', 'href'], ['img', 'src'], ['img', 'alt']], 'special' => ['linked-image', 'text-link']],
        'quiz' => [
            ['Which attribute gives a link its destination?', ['src', 'href', 'alt', 'width'], 1, 'href points to the destination.'],
            ['Which attribute gives an image its file location?', ['src', 'href', 'height', 'alt'], 0, 'src points to the image source.'],
            ['Why should an image have alt text?', ['To make it larger', 'To describe it accessibly', 'To add a border', 'To open a tab'], 1, 'Alt text describes image content.'],
            ['How do you make an image a link?', ['Put <img> inside <a>', 'Put <a> inside <title>', 'Add align to <img>', 'Use <marquee>'], 0, 'Wrap the image with an anchor.'],
            ['Which attribute can open a link in a new tab?', ['target="_blank"', 'src="new"', 'alt="new"', 'width="new"'], 0, 'target="_blank" requests a new browsing context.'],
        ],
    ],
    4 => [
        'title' => 'HTML Lists', 'level' => 'Basic',
        'objectives' => ['Distinguish unordered and ordered lists.', 'Create items using <li>.', 'Try different list marker types.'],
        'introduction' => 'Lists group related items. Ordered lists show sequence; unordered lists show a collection.',
        'explanation' => '<ul> creates bullets, <ol> creates numbered or lettered items, and each item uses <li>. The type attribute can change markers, such as A, i, square, circle, or disc.',
        'syntax' => '<ul type="square"><li>Item</li></ul> <ol type="A"><li>First</li></ol>',
        'example_html' => $page('Weekend Plans', '<h1>Weekend Plans</h1><h2>Activities</h2><ul type="circle"><li>Read</li><li>Walk</li></ul><h2>Order</h2><ol type="A"><li>Prepare</li><li>Go</li></ol>'),
        'example_css' => '', 'activity' => 'Create My Favorites with favorite foods in an unordered list, subjects in an ordered list, and hobbies in another list. Use at least two different list types.',
        'activity_html' => $page('My Favorites', '<h1>My Favorites</h1><h2>Foods</h2><ul type="square"><li>Mango</li><li>Adobo</li></ul><h2>Subjects</h2><ol type="A"><li>Science</li><li>English</li></ol><h2>Hobbies</h2><ul type="circle"><li>Drawing</li><li>Music</li></ul>'),
        'activity_css' => '', 'guided_practice' => 'Write two <li> items inside a <ul>, then change it to an <ol> and compare the markers.',
        'challenge' => 'Try Roman numerals (type="I") for one ordered list.', 'expected_result' => 'Three labeled lists with at least two marker styles.',
        'validation_rules' => ['tags' => ['h1' => 1, 'ul' => 1, 'ol' => 1, 'li' => 6], 'special' => ['three-lists', 'two-list-types']],
        'quiz' => [
            ['Which tag makes a numbered list?', ['<ul>', '<ol>', '<li>', '<p>'], 1, 'ol is an ordered list.'],
            ['Which tag makes a bulleted list?', ['<ul>', '<ol>', '<hr>', '<table>'], 0, 'ul is an unordered list.'],
            ['What wraps one list item?', ['<li>', '<list>', '<item>', '<p>'], 0, 'li marks each list item.'],
            ['Which ordered-list type uses capital letters?', ['1', 'A', 'i', 'disc'], 1, 'A displays capital letters.'],
            ['When is an ordered list useful?', ['For steps in order', 'For a page title', 'For an image', 'For a table cell'], 0, 'Use ordered lists for sequences.'],
        ],
    ],
    5 => [
        'title' => 'HTML Tables', 'level' => 'Basic',
        'objectives' => ['Build rows with <tr>.', 'Use <th> for headings and <td> for data.', 'Try border, width, cellpadding, and cellspacing attributes.'],
        'introduction' => 'Tables organize information in rows and columns.',
        'explanation' => '<table> wraps the table, <tr> is one row, <th> is a heading cell, and <td> is a data cell. The border attribute makes the grid visible; width, cellpadding, and cellspacing affect spacing in this HTML-only lesson.',
        'syntax' => '<table border="1"><tr><th>Name</th></tr><tr><td>Anna</td></tr></table>',
        'example_html' => $page('Library Books', '<h1>Library Books</h1><table border="1" cellpadding="6"><tr><th>Title</th><th>Author</th></tr><tr><td>Ocean Tales</td><td>R. Cruz</td></tr></table>'),
        'example_css' => '', 'activity' => 'Make a Student Grade Table with at least four heading columns and five student records. Show a visible border.',
        'activity_html' => $page('Student Grade Table', '<h1>Student Grade Table</h1><table border="1" cellpadding="6"><tr><th>Name</th><th>Grade</th><th>Subject</th><th>Score</th></tr><tr><td>Ana</td><td>9</td><td>Math</td><td>95</td></tr><tr><td>Ben</td><td>9</td><td>Math</td><td>91</td></tr><tr><td>Cara</td><td>9</td><td>Math</td><td>92</td></tr><tr><td>Dan</td><td>9</td><td>Math</td><td>88</td></tr><tr><td>Ella</td><td>9</td><td>Math</td><td>94</td></tr></table>'),
        'activity_css' => '', 'guided_practice' => 'Make one header row and one data row. Add more columns and rows after the first preview works.',
        'challenge' => 'Try cellpadding and cellspacing and compare the spacing.', 'expected_result' => 'A bordered four-column table with five student rows.',
        'validation_rules' => ['tags' => ['table' => 1, 'tr' => 6, 'th' => 4, 'td' => 20], 'attributes' => [['table', 'border']], 'special' => ['four-column-table']],
        'quiz' => [
            ['Which tag wraps the whole table?', ['<tr>', '<td>', '<table>', '<th>'], 2, 'table contains all rows.'],
            ['Which tag creates a table row?', ['<tr>', '<td>', '<th>', '<row>'], 0, 'tr means table row.'],
            ['Which tag is a heading cell?', ['<td>', '<th>', '<tr>', '<h1>'], 1, 'th marks a header cell.'],
            ['Which tag holds ordinary data?', ['<td>', '<th>', '<tr>', '<p>'], 0, 'td is a data cell.'],
            ['Which attribute makes a simple visible border?', ['width', 'border', 'src', 'alt'], 1, 'border adds a visible table outline.'],
        ],
    ],
    6 => [
        'title' => 'Combining Tables, Links, Images, and Lists', 'level' => 'Moderate',
        'objectives' => ['Combine earlier HTML concepts on one page.', 'Use a linked school image, an activity list, and a subject table.', 'Keep headings and descriptions clear.'],
        'introduction' => 'A useful page often combines several HTML building blocks.',
        'explanation' => 'Start with a heading and paragraph. Group activities in a list, link to a related website, show an image with alt text, and organize paired information in a table.',
        'syntax' => '<a href="https://example.com"><img src="logo.png" alt="School logo"></a> <ul><li>Club</li></ul> <table border="1"><tr><th>Subject</th></tr></table>',
        'example_html' => $page('My Favorite Places', '<h1>My Favorite Places</h1><p>Places I hope to visit.</p><img src="https://placehold.co/180x100?text=Place" alt="A favorite place"><p><a href="https://example.com">Learn more</a></p><ul><li>Park</li><li>Museum</li></ul><table border="1"><tr><th>Place</th><th>Reason</th></tr><tr><td>Park</td><td>Nature</td></tr></table>'),
        'example_css' => '', 'activity' => 'Build My School Information Page with the school name, image or logo, website link, a list of activities, and a table of subjects and teachers.',
        'activity_html' => $page('Our School', '<h1>Our School</h1><p>Welcome to our campus.</p><img src="https://placehold.co/180x100?text=School" alt="School logo"><p><a href="https://example.com">School website</a></p><h2>Activities</h2><ul><li>Sports</li><li>Music</li></ul><h2>Subjects and Teachers</h2><table border="1"><tr><th>Subject</th><th>Teacher</th></tr><tr><td>Science</td><td>Ms. Reyes</td></tr></table>'),
        'activity_css' => '', 'guided_practice' => 'Build each part separately: link, image, list, then table. Run after adding each part.',
        'challenge' => 'Link the school image to the website too.', 'expected_result' => 'A complete school information page with image, link, activity list, and teacher table.',
        'validation_rules' => ['tags' => ['h1' => 1, 'p' => 1, 'img' => 1, 'a' => 1, 'li' => 2, 'table' => 1, 'tr' => 2, 'th' => 2, 'td' => 2], 'attributes' => [['img', 'src'], ['img', 'alt'], ['a', 'href']], 'any_tags' => [['ul', 'ol']]],
        'quiz' => [
            ['Which element lists school activities?', ['<ul>', '<title>', '<td>', '<img>'], 0, 'An unordered list groups activities.'],
            ['Where does a school website address go?', ['alt', 'href', 'width', 'type'], 1, 'A link destination goes in href.'],
            ['Which tag labels table columns?', ['<td>', '<th>', '<p>', '<li>'], 1, 'Use th for table headings.'],
            ['What should a school logo include?', ['An alt description', 'An <hr>', 'A password', 'A table row'], 0, 'Alt text describes the logo.'],
            ['Which tag begins the main page heading?', ['<h1>', '<li>', '<tr>', '<a>'], 0, 'H1 is the main heading.'],
        ],
    ],
    7 => [
        'title' => 'HTML Forms', 'level' => 'Moderate',
        'objectives' => ['Explain what forms collect.', 'Connect labels with inputs.', 'Add a submit button.'],
        'introduction' => 'Forms let visitors enter information.',
        'explanation' => '<form> wraps fields. A <label> names a field. <input> accepts data, and a submit <button> sends the form. A label for="name" should match input id="name".',
        'syntax' => '<form><label for="name">Name</label><input id="name" type="text"><button type="submit">Submit</button></form>',
        'example_html' => $page('Club Sign-up', '<h1>Club Sign-up</h1><form><label for="member">Member name</label><input id="member" type="text"><br><label for="club">Club</label><input id="club" type="text"><br><button type="submit">Join</button></form>'),
        'example_css' => '', 'activity' => 'Create a student registration form with labeled Name, Grade, Section, and Age fields plus a Submit button.',
        'activity_html' => $page('Student Registration', '<h1>Student Registration</h1><form><label for="name">Name</label><input id="name" type="text"><br><label for="grade">Grade</label><input id="grade" type="text"><br><label for="section">Section</label><input id="section" type="text"><br><label for="age">Age</label><input id="age" type="number"><br><button type="submit">Submit</button></form>'),
        'activity_css' => '', 'guided_practice' => 'Make one labeled text field and a button first; then add the remaining fields.',
        'challenge' => 'Use type="number" for the Age field.', 'expected_result' => 'Four labeled fields and a submit button.',
        'validation_rules' => ['tags' => ['form' => 1, 'label' => 4, 'input' => 4, 'button' => 1], 'special' => ['associated-labels', 'submit-button']],
        'quiz' => [
            ['Which tag wraps form controls?', ['<form>', '<table>', '<div>', '<body>'], 0, 'A form groups its controls.'],
            ['Which tag names an input?', ['<label>', '<source>', '<span>', '<img>'], 0, 'A label names the field.'],
            ['What should label for match?', ['Input id', 'Input value', 'Page title', 'Button text'], 0, 'for connects to an input id.'],
            ['Which element lets a visitor type?', ['<input>', '<hr>', '<th>', '<marquee>'], 0, 'Inputs collect typed values.'],
            ['Which button type submits a form?', ['reset', 'button', 'submit', 'text'], 2, 'type="submit" submits the form.'],
        ],
    ],
    8 => [
        'title' => 'HTML Form Input Types', 'level' => 'Moderate',
        'objectives' => ['Choose text, email, password, radio, and checkbox inputs.', 'Use name, value, and placeholder.', 'Build a larger labeled form.'],
        'introduction' => 'Different input types collect different kinds of answers.',
        'explanation' => 'Email fields expect email addresses. Password fields hide characters. Radio buttons share a name so one can be selected; checkboxes allow several choices. name identifies submitted data, value is its stored choice, and placeholder is a hint.',
        'syntax' => '<input type="email" name="email" placeholder="you@example.com"> <input type="radio" name="group" value="a">',
        'example_html' => $page('Club Survey', '<h1>Club Survey</h1><form><label for="visitor">Name</label><input id="visitor" type="text" name="visitor" placeholder="Your name"><br><label for="mail">Email</label><input id="mail" type="email" name="mail"><br><label><input type="radio" name="time" value="morning"> Morning</label><label><input type="radio" name="time" value="afternoon"> Afternoon</label><br><label><input type="checkbox" name="updates" value="yes"> Updates</label><button type="submit">Send</button></form>'),
        'example_css' => '', 'activity' => 'Create a complete Student Registration Form with full name, email, password, gender choices, three hobbies, and a Submit button.',
        'activity_html' => $page('Student Registration', '<h1>Student Registration</h1><form><label for="full">Full name</label><input id="full" type="text" name="full" placeholder="Full name"><br><label for="email">Email</label><input id="email" type="email" name="email"><br><label for="password">Password</label><input id="password" type="password" name="password"><br><label><input type="radio" name="gender" value="female"> Female</label><label><input type="radio" name="gender" value="male"> Male</label><br><label><input type="checkbox" name="hobby1" value="reading"> Reading</label><label><input type="checkbox" name="hobby2" value="sports"> Sports</label><label><input type="checkbox" name="hobby3" value="music"> Music</label><br><button type="submit">Submit</button></form>'),
        'activity_css' => '', 'guided_practice' => 'Begin with labeled name and email fields. Add a password field, then a named radio group and checkboxes.',
        'challenge' => 'Add a placeholder to the full-name field and values to the choices.', 'expected_result' => 'A registration form with the required field types and three hobbies.',
        'validation_rules' => ['tags' => ['form' => 1, 'button' => 1, 'label' => 5], 'input_types' => ['text' => 1, 'email' => 1, 'password' => 1, 'radio' => 2, 'checkbox' => 3], 'attributes' => [['input', 'name']], 'special' => ['submit-button', 'radio-group']],
        'quiz' => [
            ['Which input type hides entered characters?', ['text', 'email', 'password', 'radio'], 2, 'Password fields obscure characters.'],
            ['Which choice type allows only one in a named group?', ['checkbox', 'radio', 'text', 'email'], 1, 'Radio choices with one name form a group.'],
            ['Which choice type allows multiple selections?', ['checkbox', 'password', 'email', 'submit'], 0, 'Checkboxes can be selected independently.'],
            ['What is placeholder for?', ['A field hint', 'A page link', 'An image source', 'A table heading'], 0, 'Placeholder gives a short input hint.'],
            ['What does value provide for a choice?', ['Its submitted value', 'Its width', 'Its label color', 'Its page title'], 0, 'value identifies the chosen answer.'],
        ],
    ],
    9 => [
        'title' => 'DIV and SPAN', 'level' => 'Moderate',
        'objectives' => ['Group page sections with div.', 'Mark smaller text with span.', 'Build an organized profile page.'],
        'introduction' => 'Grouping elements help organize larger pages.',
        'explanation' => '<div> groups a section or block of content. <span> marks a small part inside a line of text. Neither adds meaning by itself; clear headings and labels help readers understand each section.',
        'syntax' => '<div><h2>About</h2><p>I like <span>science</span>.</p></div>',
        'example_html' => $page('Club Profile', '<div><h1>Club Profile</h1></div><div><h2>About</h2><p>We enjoy <span>robotics</span>.</p></div><div><h2>Events</h2><p>Meet every Friday.</p></div><div><h2>Contact</h2><p>Email our adviser.</p></div>'),
        'example_css' => '', 'activity' => 'Build a page with separate Header, About Me, Hobbies, and Contact sections. Use div elements to organize it and span within some text.',
        'activity_html' => $page('My Profile', '<div><h1>My Profile</h1></div><div><h2>About Me</h2><p>I am a <span>student</span>.</p></div><div><h2>Hobbies</h2><p>Drawing and music.</p></div><div><h2>Contact</h2><p>Email me at hello@example.com.</p></div>'),
        'activity_css' => '', 'guided_practice' => 'Wrap one heading and paragraph in a div. Add more div sections, then wrap one phrase in span.',
        'challenge' => 'Give each section a clear H2 heading.', 'expected_result' => 'Four visible profile sections, with one highlighted phrase ready for later styling.',
        'validation_rules' => ['tags' => ['div' => 4, 'span' => 1, 'h1' => 1, 'h2' => 3, 'p' => 3]],
        'quiz' => [
            ['Which tag groups a block or section?', ['<div>', '<span>', '<br>', '<td>'], 0, 'div groups block content.'],
            ['Which tag marks a short phrase?', ['<div>', '<span>', '<table>', '<form>'], 1, 'span marks inline text.'],
            ['Does div automatically give a section a heading?', ['Yes', 'Only in forms', 'No', 'Only with CSS'], 2, 'Add a heading separately.'],
            ['Where might span be useful?', ['Around one word in a sentence', 'Around the whole HTML document', 'As a table row', 'As a page title'], 0, 'span is an inline grouping element.'],
            ['What helps identify grouped sections to readers?', ['Clear headings', 'Empty tags', 'Missing labels', 'Broken links'], 0, 'Headings make sections understandable.'],
        ],
    ],
    10 => [
        'title' => 'Audio and Video', 'level' => 'Moderate',
        'objectives' => ['Embed audio and video.', 'Use source with compatible media types.', 'Add controls and useful size attributes.'],
        'introduction' => 'Web pages can include sound and moving pictures.',
        'explanation' => '<audio> and <video> hold media. Nested <source> elements name files and media types so browsers can choose a supported format. controls displays player controls. autoplay may be blocked by browsers, and loop repeats playback.',
        'syntax' => '<audio controls><source src="sound.mp3" type="audio/mpeg"></audio> <video width="400" controls><source src="clip.mp4" type="video/mp4"></video>',
        'example_html' => $page('Nature Media', '<h1>Nature Media</h1><p>Listen and watch.</p><img src="https://placehold.co/180x100?text=Nature" alt="Trees"><audio controls><source src="nature.mp3" type="audio/mpeg"></audio><video width="320" controls><source src="nature.mp4" type="video/mp4"></video><p><a href="https://example.com">More nature</a></p>'),
        'example_css' => '', 'activity' => 'Create My Multimedia Page with a heading, description, image, audio player, video player, and link. Use source and controls for both players.',
        'activity_html' => $page('My Multimedia Page', '<h1>My Multimedia Page</h1><p>Media I enjoy.</p><img src="https://placehold.co/180x100?text=Media" alt="Media poster"><audio controls><source src="music.mp3" type="audio/mpeg"></audio><video width="320" controls><source src="video.mp4" type="video/mp4"></video><p><a href="https://example.com">Read more</a></p>'),
        'activity_css' => '', 'guided_practice' => 'Add audio with controls and a source. Repeat with video, then add an image and link.',
        'challenge' => 'Add a second source format or loop to one player.', 'expected_result' => 'A page with a picture, audio controls, video controls, and a link. Local sample files may not play until added.',
        'validation_rules' => ['tags' => ['h1' => 1, 'p' => 1, 'img' => 1, 'audio' => 1, 'video' => 1, 'source' => 2, 'a' => 1], 'attributes' => [['audio', 'controls'], ['video', 'controls'], ['source', 'src'], ['source', 'type']]],
        'quiz' => [
            ['Which tag embeds a sound player?', ['<audio>', '<video>', '<img>', '<source>'], 0, 'audio is for sound.'],
            ['Which tag embeds a video player?', ['<audio>', '<video>', '<a>', '<form>'], 1, 'video is for moving pictures.'],
            ['Why place source inside media elements?', ['To list compatible files', 'To draw a border', 'To add a heading', 'To center text'], 0, 'A source names a media file and its type.'],
            ['Which attribute shows play and pause controls?', ['loop', 'width', 'controls', 'alt'], 2, 'controls enables browser player controls.'],
            ['Why might autoplay not start?', ['Browsers may block it', 'HTML forbids audio', 'Images are missing', 'The page has headings'], 0, 'Browsers often restrict autoplay.'],
        ],
    ],
    11 => [
        'title' => 'Introduction to CSS', 'level' => 'Advanced',
        'objectives' => ['Distinguish HTML structure from CSS presentation.', 'Compare inline, internal, and external CSS.', 'Style text color, background color, size, and alignment.'],
        'introduction' => 'HTML supplies content. CSS controls how that content looks.',
        'explanation' => 'Inline CSS goes in a style attribute, internal CSS goes in a <style> tag, and external CSS goes in a linked file. External CSS is easiest to reuse and maintain; inline CSS is quick but hard to maintain, while internal CSS affects one page.',
        'syntax' => '<h1 style="color: blue">Hello</h1> <style>h1 { color: blue; }</style> <link rel="stylesheet" href="styles.css">',
        'example_html' => $page('Our Club', '<h1>Our Club</h1><p>Welcome to the club.</p>'),
        'example_css' => 'body { background-color: #f0f7ff; text-align: center; } h1 { color: navy; font-size: 32px; }',
        'activity' => 'Create a webpage and apply text color, background color, font size, and text alignment. Use the CSS editor; try inline or internal CSS as an optional comparison.',
        'activity_html' => $page('My Styled Page', '<h1>My Styled Page</h1><p>Learning CSS is exciting.</p>'),
        'activity_css' => 'body { background-color: #eef2ff; text-align: center; } h1 { color: #4338ca; font-size: 36px; }',
        'guided_practice' => 'Add one rule to styles.css, run, and compare the page. Try changing one property value at a time.',
        'challenge' => 'Try all three ways of adding CSS and explain which is easiest to maintain.', 'expected_result' => 'A simple page with a colored background, styled heading, larger text, and aligned content.',
        'validation_rules' => ['tags' => ['h1' => 1, 'p' => 1], 'css_properties' => ['color', 'background-color', 'font-size', 'text-align']],
        'quiz' => [
            ['What does CSS mainly control?', ['Presentation', 'Account login', 'Database records', 'Image files'], 0, 'CSS controls visual presentation.'],
            ['Where is inline CSS written?', ['In style="..."', 'In <title>', 'In <body bgcolor>', 'In href'], 0, 'An element style attribute holds inline CSS.'],
            ['Where is internal CSS written?', ['<style>', '<table>', '<p>', '<form>'], 0, 'A style element holds internal CSS.'],
            ['Which file is linked for external CSS?', ['A .css file', 'A .mp3 file', 'A .png file', 'A .html file'], 0, 'External CSS lives in a stylesheet.'],
            ['Which CSS property changes text size?', ['font-size', 'background-color', 'margin', 'border'], 0, 'font-size changes text size.'],
        ],
    ],
    12 => [
        'title' => 'CSS Selectors', 'level' => 'Advanced',
        'objectives' => ['Use element selectors.', 'Style at least two classes.', 'Style an ID selector.'],
        'introduction' => 'Selectors tell CSS which HTML elements to style.',
        'explanation' => 'An element selector uses a tag name, such as p. A class selector begins with a dot and can style many elements. An ID selector begins with # and identifies one element on a page.',
        'syntax' => 'p { color: blue; } .student { color: green; } #title { color: red; }',
        'example_html' => $page('Club Members', '<h1 id="club-title">Club Members</h1><p class="leader">Team leader</p><p class="member">New member</p>'),
        'example_css' => 'p { font-size: 18px; } .leader { color: green; } .member { color: blue; } #club-title { color: purple; }',
        'activity' => 'Style a student profile using an element selector, at least two different classes, and one ID. Apply those selectors to matching HTML elements.',
        'activity_html' => $page('Student Profile', '<h1 id="profile-title">Student Profile</h1><p class="intro">Hello, I am Alex.</p><p class="favorite">I like science.</p>'),
        'activity_css' => 'p { font-size: 18px; } .intro { color: #2563eb; } .favorite { color: #15803d; } #profile-title { text-align: center; }',
        'guided_practice' => 'Start with a p rule. Add class="..." to two elements, then id="..." to one heading and match each in CSS.',
        'challenge' => 'Reuse one class on a second element and see both change.', 'expected_result' => 'A profile with paragraph styling, two distinct class styles, and one ID style.',
        'validation_rules' => ['tags' => ['h1' => 1, 'p' => 2], 'special' => ['element-selector', 'two-classes', 'id-selector']],
        'quiz' => [
            ['Which selector targets all paragraphs?', ['p', '.p', '#p', '*p'], 0, 'A tag name is an element selector.'],
            ['What begins a class selector?', ['.', '#', '@', '/'], 0, 'Classes begin with a dot in CSS.'],
            ['What begins an ID selector?', ['.', '#', ':', '*'], 1, 'IDs begin with # in CSS.'],
            ['Can a class be reused?', ['Yes', 'No', 'Only on headings', 'Only in forms'], 0, 'Multiple elements can share a class.'],
            ['Which HTML attribute matches #profile?', ['id="profile"', 'class="profile"', 'src="profile"', 'href="profile"'], 0, 'An ID selector matches the id attribute.'],
        ],
    ],
    13 => [
        'title' => 'CSS Box Model', 'level' => 'Advanced',
        'objectives' => ['Identify content, padding, border, and margin.', 'Set box width and spacing.', 'Build three content boxes.'],
        'introduction' => 'Every element is a box with content and space around it.',
        'explanation' => 'Content sits inside padding. A border surrounds the padding. Margin is space outside the border. Width sets the content area unless box-sizing changes how width is calculated.',
        'syntax' => '.box { width: 300px; padding: 20px; border: 2px solid black; margin: 20px; }',
        'example_html' => $page('Book Cards', '<h1>Book Cards</h1><div class="book">Book One</div><div class="book">Book Two</div><div class="book">Book Three</div>'),
        'example_css' => '.book { width: 220px; padding: 18px; border: 2px solid #334155; margin: 14px; }',
        'activity' => 'Create three content boxes. Set and change their width, padding, border, and margin. Observe the space inside and outside each border.',
        'activity_html' => $page('My Three Boxes', '<h1>My Three Boxes</h1><div class="box">Content 1</div><div class="box">Content 2</div><div class="box">Content 3</div>'),
        'activity_css' => '.box { width: 250px; padding: 20px; border: 2px solid #4f46e5; margin: 16px; background-color: #eef2ff; }',
        'guided_practice' => 'Make one div with a class. Add width, padding, border, then margin. Duplicate it twice.',
        'challenge' => 'Try box-sizing: border-box and compare the total width.', 'expected_result' => 'Three visible boxes with space between content, border, and neighboring boxes.',
        'validation_rules' => ['tags' => ['div' => 3], 'css_properties' => ['width', 'padding', 'border', 'margin']],
        'quiz' => [
            ['What is inside the padding?', ['Content', 'Margin', 'Border', 'Another page'], 0, 'Padding surrounds the content.'],
            ['What surrounds the padding?', ['Border', 'Margin', 'Title', 'Image'], 0, 'The border is outside padding.'],
            ['Which property adds space outside a border?', ['margin', 'padding', 'width', 'color'], 0, 'Margin is outside the border.'],
            ['Which property adds space inside a border?', ['padding', 'margin', 'height', 'display'], 0, 'Padding is inside the border.'],
            ['Which property controls a box’s width?', ['width', 'border', 'color', 'gap'], 0, 'width sets its horizontal size.'],
        ],
    ],
    14 => [
        'title' => 'CSS Grid', 'level' => 'Advanced',
        'objectives' => ['Create a grid container.', 'Set three columns on larger screens.', 'Use gap and six gallery items.'],
        'introduction' => 'CSS Grid places items into rows and columns.',
        'explanation' => 'display: grid turns a container into a grid. grid-template-columns defines its columns, and gap sets space between items. A media query can change the number of columns for smaller screens.',
        'syntax' => '.gallery { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }',
        'example_html' => $page('Color Swatches', '<h1>Color Swatches</h1><div class="swatches"><div>Red</div><div>Blue</div><div>Green</div></div>'),
        'example_css' => '.swatches { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; } .swatches div { padding: 20px; background: #e0e7ff; }',
        'activity' => 'Create a photo gallery with at least six items, a three-column Grid layout on larger screens, and visible spacing between items.',
        'activity_html' => $page('Photo Gallery', '<h1>Photo Gallery</h1><div class="gallery"><div><img src="https://placehold.co/140x90?text=1" alt="Photo 1"></div><div><img src="https://placehold.co/140x90?text=2" alt="Photo 2"></div><div><img src="https://placehold.co/140x90?text=3" alt="Photo 3"></div><div><img src="https://placehold.co/140x90?text=4" alt="Photo 4"></div><div><img src="https://placehold.co/140x90?text=5" alt="Photo 5"></div><div><img src="https://placehold.co/140x90?text=6" alt="Photo 6"></div></div>'),
        'activity_css' => '.gallery { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; } .gallery div { padding: 8px; border: 1px solid #ddd; } .gallery img { max-width: 100%; } @media (max-width: 600px) { .gallery { grid-template-columns: 1fr; } }',
        'guided_practice' => 'Put three items in a container. Add display:grid, three columns, and gap; then expand to six items.',
        'challenge' => 'Use a media query to switch to one column on phones.', 'expected_result' => 'Six gallery items arranged in three spaced columns at wider sizes.',
        'validation_rules' => ['tags' => ['img' => 6], 'css_properties' => ['display', 'grid-template-columns', 'gap'], 'special' => ['grid-three-columns', 'six-gallery-items']],
        'quiz' => [
            ['Which declaration enables Grid?', ['display: grid', 'position: grid', 'grid: true', 'layout: grid'], 0, 'display:grid creates a grid container.'],
            ['Which property sets columns?', ['grid-template-columns', 'gap', 'margin', 'border'], 0, 'grid-template-columns defines columns.'],
            ['Which property spaces grid items?', ['gap', 'color', 'font-size', 'width'], 0, 'gap adds space between tracks.'],
            ['What does 1fr represent?', ['A fraction of available space', 'One fixed pixel', 'A font', 'A file'], 0, 'fr divides available grid space.'],
            ['What can change columns on small screens?', ['A media query', 'A table row', 'An alt attribute', 'A title'], 0, 'Media queries adapt layouts to screen sizes.'],
        ],
    ],
    15 => [
        'title' => 'Navigation and Multi-Page Websites', 'level' => 'Advanced',
        'objectives' => ['Connect four HTML files with relative links.', 'Reuse HTML and CSS skills from all levels.', 'Build a small Home, About, Gallery, and Contact website.'],
        'introduction' => 'A website can have several pages connected by navigation.',
        'explanation' => 'Relative links such as about.html open another file in the same project. Keep navigation consistent on every page. Reuse headings, paragraphs, formatting, images, lists, tables, forms, media, div/span, CSS classes and IDs, box model, and Grid.',
        'syntax' => '<nav><a href="index.html">Home</a> <a href="about.html">About</a> <a href="gallery.html">Gallery</a> <a href="contact.html">Contact</a></nav>',
        'example_html' => $page('Museum Home', '<nav><a href="index.html">Home</a> <a href="about.html">About</a></nav><h1>Museum Home</h1><p>Explore our exhibits.</p>'),
        'example_css' => 'nav { display: flex; gap: 16px; padding: 12px; background: #e0e7ff; } nav a { color: #1e3a8a; }',
        'activity' => 'Build a four-page website: Home, About, Gallery, Contact. Connect all pages with relative navigation. Across the site include document structure, headings, paragraphs, formatting, images, links, lists, tables, forms, div/span, audio or video, classes, IDs, Box Model, and CSS Grid.',
        'activity_html' => $page('My Mini Website', '<nav><a href="index.html">Home</a> <a href="about.html">About</a> <a href="gallery.html">Gallery</a> <a href="contact.html">Contact</a></nav><h1>My Mini Website</h1><p>Explore my four pages.</p><div class="cards"><div>About me</div><div>My gallery</div><div>Contact</div></div>'),
        'activity_css' => 'body { font-family: Arial, sans-serif; margin: 20px; } nav { display: flex; gap: 12px; padding: 12px; border: 1px solid #888; } .cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 20px 0; } .cards div { padding: 12px; border: 1px solid #aaa; }',
        'guided_practice' => 'Write the Home page and its nav first. Add About, Gallery, and Contact files, then test every link in the preview.',
        'challenge' => 'Make the navigation and Grid responsive for phones.', 'expected_result' => 'Four connected pages with consistent navigation and content from every level.',
        'validation_rules' => ['tags' => ['html' => 4, 'head' => 4, 'title' => 4, 'body' => 4, 'nav' => 1, 'a' => 4], 'css_properties' => ['display', 'grid-template-columns', 'gap', 'padding', 'border', 'margin'], 'special' => ['four-pages', 'site-concepts', 'grid-three-columns']],
        'quiz' => [
            ['Which href links to a file in the same project?', ['about.html', 'https://example.com', 'mailto:a@b.com', '#top'], 0, 'about.html is a relative file link.'],
            ['Which tag groups navigation links?', ['<nav>', '<table>', '<video>', '<form>'], 0, 'nav marks navigation.'],
            ['Which page should collect contact information?', ['Contact', 'Gallery', 'Home', 'About'], 0, 'The Contact page commonly contains a form.'],
            ['Which layout is useful for a photo gallery?', ['CSS Grid', 'A password input', 'A marquee', 'A title tag'], 0, 'Grid lays out many gallery items.'],
            ['Why repeat navigation on every page?', ['Visitors can move between pages', 'To hide links', 'To remove CSS', 'To create audio'], 0, 'Consistent navigation helps visitors move around.'],
        ],
    ],
];
