<?php

return [
    1 => [
        'steps' => ['Keep the complete HTML document in index.html.', 'Inside <body>, add one main heading and one paragraph.', 'Open styles.css, style the page, then press Run.'],
        'focus' => [['code' => '<h1>', 'meaning' => 'Creates the main heading.'], ['code' => '<p>', 'meaning' => 'Creates the paragraph.'], ['code' => 'color', 'meaning' => 'Changes the heading text color.']],
        'html_hint' => "<h1>Your page title</h1>\n<p>Write one sentence about your page.</p>",
        'css_hint' => "body { padding: 20px; }\nh1 { color: royalblue; }",
        'tip' => 'Text that students can see belongs between the opening and closing body tags.',
    ],
    2 => [
        'steps' => ['Use the existing doctype, <html>, <head>, and <body> in index.html.', 'Inside <body>, create a header, a main section, and a footer.', 'Add your own headings and paragraph, then give the header and footer different backgrounds.'],
        'focus' => [['code' => '<header>', 'meaning' => 'Holds the page title.'], ['code' => '<main>', 'meaning' => 'Holds the welcome message.'], ['code' => '<footer>', 'meaning' => 'Holds a closing note.'], ['code' => 'background-color', 'meaning' => 'Changes the color behind a section.']],
        'html_hint' => "<!-- Inside the existing <head>: -->\n<title>Your page title</title>\n<link rel=\"stylesheet\" href=\"styles.css\">\n\n<!-- Inside the existing <body>: -->\n<header><h1>Your school name</h1></header>\n<main><h2>Your welcome heading</h2><p>Write your message.</p></main>\n<footer><p>Add your credit.</p></footer>",
        'css_hint' => "header {\n  background-color: steelblue;\n  color: white;\n  padding: 24px;\n}\nmain { padding: 24px; }\nfooter { background-color: lavender; }\n/* Choose your own spacing and colors. */",
        'tip' => 'The head describes the page; the body contains everything shown on the page.',
    ],
    3 => [
        'steps' => ['Use one <h1> for the article title.', 'Add <h2> headings for the main sections.', 'Write a <p> paragraph below each heading.'],
        'focus' => [['code' => '<h1>', 'meaning' => 'Creates the article title.'], ['code' => '<h2>', 'meaning' => 'Creates section headings.'], ['code' => 'line-height', 'meaning' => 'Improves paragraph readability.']],
        'html_hint' => "<article>\n  <h1>Your article title</h1>\n  <p>Write an introduction.</p>\n  <h2>Your first section</h2>\n  <p>Explain this section.</p>\n  <!-- Add another <h2> and <p>. -->\n</article>",
        'css_hint' => "body { line-height: 1.6; }\nh1 { color: darkslateblue; }\nh2 { color: royalblue; }",
        'tip' => 'Do not choose heading levels for their size; use them to show the content order.',
    ],
    4 => [
        'steps' => ['Write a short reminder in a paragraph.', 'Use <strong> for important words and <em> for emphasis.', 'Try <mark> for highlighted text and <code> for a code term.'],
        'focus' => [['code' => '<strong>', 'meaning' => 'Marks important text.'], ['code' => '<em>', 'meaning' => 'Adds meaningful emphasis.'], ['code' => '<mark>', 'meaning' => 'Highlights text.']],
        'html_hint' => "<h1>Your reminders title</h1>\n<p><strong>Important text</strong> is easy to notice.</p>\n<p>Use <em>emphasis</em> and <mark>highlighting</mark>.</p>\n<p>The <code>&lt;p&gt;</code> tag makes a paragraph.</p>",
        'css_hint' => "mark { background: lightyellow; }\ncode { background: lavender; padding: 3px; }",
        'tip' => 'Semantic formatting tells the browser why text is important, not only how it looks.',
    ],
    5 => [
        'steps' => ['Add an image with src and a useful alt description.', 'Add a short heading and description below it.', 'Create a link with <a> and use href for its destination.'],
        'focus' => [['code' => '<img>', 'meaning' => 'Displays an image.'], ['code' => 'alt', 'meaning' => 'Describes the image accessibly.'], ['code' => '<a>', 'meaning' => 'Creates a link.']],
        'html_hint' => "<div class=\"card\">\n  <img src=\"your-image.jpg\" alt=\"Describe what is shown\">\n  <h1>Your place title</h1>\n  <p>Write a short description.</p>\n  <a href=\"https://example.com\">Visit a page</a>\n</div>",
        'css_hint' => "img { width: 100%; border-radius: 8px; }\na { color: royalblue; }\n/* Set a width for .card. */",
        'tip' => 'The alt text should explain the image to someone who cannot see it.',
    ],
    6 => [
        'steps' => ['Use <ul> when the order does not matter.', 'Place every item inside an <li> tag.', 'Use <ol> for steps that must be followed in order.'],
        'focus' => [['code' => '<ul>', 'meaning' => 'Creates an unordered list.'], ['code' => '<ol>', 'meaning' => 'Creates a numbered list.'], ['code' => '<li>', 'meaning' => 'Creates each list item.']],
        'html_hint' => "<h1>Your study plan</h1>\n<h2>Subjects</h2>\n<ul>\n  <li>Your first subject</li>\n  <!-- Add more subjects. -->\n</ul>\n<h2>Steps</h2>\n<ol>\n  <li>Your first study step</li>\n  <!-- Add more steps. -->\n</ol>",
        'css_hint' => "body { line-height: 1.6; }\nli { margin-bottom: 8px; }",
        'tip' => 'Only list items should be direct children of ul and ol elements.',
    ],
    7 => [
        'steps' => ['Create a <table> and describe it with <caption>.', 'Build the heading row with <th> cells.', 'Add each schedule entry as a <tr> containing <td> cells.'],
        'focus' => [['code' => '<th>', 'meaning' => 'Creates a table heading cell.'], ['code' => '<td>', 'meaning' => 'Creates a table data cell.'], ['code' => 'border-collapse', 'meaning' => 'Joins table borders cleanly.']],
        'html_hint' => "<table>\n  <caption>Your schedule title</caption>\n  <thead><tr><th>Day</th><th>Subject</th><th>Time</th></tr></thead>\n  <tbody><tr><td>Your day</td><td>Your subject</td><td>Your time</td></tr></tbody>\n  <!-- Add more rows. -->\n</table>",
        'css_hint' => "table { width: 100%; border-collapse: collapse; }\nth, td { border: 1px solid gray; padding: 8px; }\nth { background: lavender; }",
        'tip' => 'Every row should contain the same number of cells so the columns line up.',
    ],
    8 => [
        'steps' => ['Start with a <form> and add a heading.', 'Connect each <label for> value to the matching input id.', 'Use suitable input types and finish with a submit button.'],
        'focus' => [['code' => '<label>', 'meaning' => 'Names an input field.'], ['code' => '<input>', 'meaning' => 'Collects typed information.'], ['code' => '<button>', 'meaning' => 'Submits the form.']],
        'html_hint' => "<form>\n  <h1>Your form title</h1>\n  <label for=\"student-name\">Student name</label>\n  <input id=\"student-name\" type=\"text\">\n  <label for=\"student-email\">Email</label>\n  <input id=\"student-email\" type=\"email\">\n  <label for=\"grade\">Grade</label>\n  <select id=\"grade\"><option>Choose a grade</option></select>\n  <button type=\"submit\">Your button text</button>\n</form>",
        'css_hint' => "label { display: block; margin-top: 12px; }\ninput, select, button { width: 100%; padding: 8px; }\n/* Choose a color for the button. */",
        'tip' => 'Labels make forms easier to understand and use with assistive technology.',
    ],
    9 => [
        'steps' => ['Give your HTML section a class name.', 'Select that class in styles.css using a dot.', 'Add background, padding, and text styles, then press Run.'],
        'focus' => [['code' => 'class', 'meaning' => 'Gives an element a reusable name.'], ['code' => '.profile-card', 'meaning' => 'Selects that class in CSS.'], ['code' => 'padding', 'meaning' => 'Adds space inside the card.']],
        'html_hint' => "<section class=\"profile-card\">\n  <p class=\"eyebrow\">YOUR LABEL</p>\n  <h1>Your name</h1>\n  <p>Write a short introduction.</p>\n  <button>Your button text</button>\n</section>",
        'css_hint' => "body { background: lavender; }\n.profile-card { padding: 20px; background: white; border-radius: 10px; }\nbutton { background: steelblue; color: white; }",
        'tip' => 'A class can be reused. In CSS, write a dot before the class name.',
    ],
    10 => [
        'steps' => ['Choose readable colors for the page background and text.', 'Set a font-family on body so the whole page inherits it.', 'Adjust font size, line height, or letter spacing for important text.'],
        'focus' => [['code' => 'color', 'meaning' => 'Changes text color.'], ['code' => 'font-family', 'meaning' => 'Chooses the typeface.'], ['code' => 'font-size', 'meaning' => 'Changes text size.']],
        'html_hint' => "<article>\n  <p class=\"label\">YOUR TOPIC</p>\n  <h1>Your article title</h1>\n  <p class=\"intro\">Write an opening sentence.</p>\n  <p>Add the rest of your article.</p>\n</article>",
        'css_hint' => "body { font-family: Georgia, serif; color: darkslategray; }\n.label { letter-spacing: 2px; }\n.intro { font-size: 20px; color: royalblue; }",
        'tip' => 'Dark text on a light background is usually easiest to read.',
    ],
    11 => [
        'steps' => ['Create several card sections in HTML.', 'Add padding inside each card and margin outside it.', 'Add a border and use box-sizing so sizing stays predictable.'],
        'focus' => [['code' => 'padding', 'meaning' => 'Adds space inside the border.'], ['code' => 'margin', 'meaning' => 'Adds space outside the border.'], ['code' => 'border', 'meaning' => 'Draws the card edge.']],
        'html_hint' => "<h1>Your clubs heading</h1>\n<div class=\"cards\">\n  <section><h2>Choose a club</h2><p>Describe it.</p></section>\n  <!-- Add two more <section> cards. -->\n</div>",
        'css_hint' => "* { box-sizing: border-box; }\nsection { margin: 12px 0; border: 2px solid slateblue; padding: 16px; background: lavender; }",
        'tip' => 'Padding is inside the border; margin creates space outside the border.',
    ],
    12 => [
        'steps' => ['Place the items that should align inside one parent container.', 'Set display: flex on that parent.', 'Use gap, justify-content, and align-items to control spacing and alignment.'],
        'focus' => [['code' => 'display: flex', 'meaning' => 'Places child items in a flexible row.'], ['code' => 'gap', 'meaning' => 'Adds space between items.'], ['code' => 'justify-content', 'meaning' => 'Controls horizontal alignment.']],
        'html_hint' => "<nav><strong>Your site name</strong><div><a href=\"#\">One link</a></div></nav>\n<h1>Your topics heading</h1>\n<div class=\"cards\">\n  <article>First topic</article>\n  <!-- Add more cards and navigation links. -->\n</div>",
        'css_hint' => "nav { display: flex; justify-content: space-between; align-items: center; }\n.cards { display: flex; gap: 12px; }\n.cards article { flex: 1; }",
        'tip' => 'Flexbox affects the direct children of the element with display: flex.',
    ],
    13 => [
        'steps' => ['Put all gallery cards inside one container.', 'Set display: grid on the gallery.', 'Create columns with grid-template-columns and space them with gap.'],
        'focus' => [['code' => 'display: grid', 'meaning' => 'Turns the container into a grid.'], ['code' => 'grid-template-columns', 'meaning' => 'Defines the columns.'], ['code' => 'gap', 'meaning' => 'Adds space between grid items.']],
        'html_hint' => "<h1>Your gallery title</h1>\n<div class=\"gallery\">\n  <article>One project</article>\n  <!-- Add five more <article> cards. -->\n</div>",
        'css_hint' => ".gallery { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }\n.gallery article { background: steelblue; color: white; padding: 16px; }",
        'tip' => 'The fr unit divides the available space into equal fractions.',
    ],
    14 => [
        'steps' => ['Build the desktop layout with two Grid columns.', 'Add a media query for screens up to 600px wide.', 'Inside it, change the layout to one column and test a narrow window.'],
        'focus' => [['code' => '@media', 'meaning' => 'Applies styles at a chosen screen size.'], ['code' => 'max-width', 'meaning' => 'Sets the breakpoint limit.'], ['code' => '1fr', 'meaning' => 'Creates one flexible column.']],
        'html_hint' => "<header><h1>Your news title</h1></header>\n<main>\n  <article><h2>Your story heading</h2><p>Write the story.</p></article>\n  <aside><h2>Your links heading</h2><p>First link<br>Second link</p></aside>\n</main>",
        'css_hint' => "main { display: grid; grid-template-columns: 2fr 1fr; gap: 16px; }\n@media (max-width: 600px) {\n  main { grid-template-columns: 1fr; }\n}\n/* Add colors and padding to your sections. */",
        'tip' => 'A media query applies its rules only when its screen condition is true.',
    ],
    15 => [
        'steps' => ['Plan the page as header, navigation, main sections, and footer.', 'Use Flexbox for navigation and Grid for the project cards.', 'Add a media query so the cards stack on a phone, then test every link and section.'],
        'focus' => [['code' => '<nav>', 'meaning' => 'Contains navigation links.'], ['code' => 'display: grid', 'meaning' => 'Lays out the project cards.'], ['code' => '@media', 'meaning' => 'Makes the page responsive.']],
        'html_hint' => "<header>\n  <nav><strong>Your site name</strong><a href=\"#projects\">Projects</a></nav>\n  <div class=\"hero\"><h1>Your message</h1><p>Add an introduction.</p></div>\n</header>\n<main id=\"projects\">\n  <h2>Your projects</h2>\n  <div class=\"grid\"><article>One project</article><!-- Add more cards. --></div>\n</main>\n<footer>Add a closing line.</footer>",
        'css_hint' => "nav { display: flex; justify-content: space-between; }\n.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }\n@media (max-width: 600px) { .grid { grid-template-columns: 1fr; } }\n/* Choose colors and spacing for each section. */",
        'tip' => 'Build one section at a time and press Run after each small change.',
    ],
];
