import { Head, Link } from '@inertiajs/react';
import { CheckCircle2, FlaskConical, LockKeyhole } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

type CaseStudy = { id: number; number: number; title: string; scenario: string; objectives: string[]; status: string; unlocked: boolean };
export default function CaseStudies({ caseStudies, lessonsComplete }: { caseStudies: CaseStudy[]; lessonsComplete: boolean }) {
    return <><Head title="Case Studies" /><main className="soft-grid min-h-full p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><Badge variant="outline">Apply what you learned</Badge><h1 className="mt-3 text-3xl font-bold">Case studies</h1><p className="mt-2 max-w-2xl text-muted-foreground">Five practical projects that grow from a personal profile into a complete responsive website.</p></header>{!lessonsComplete && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Complete all required lessons to unlock the first case study. Teachers can always preview the full set.</div>}<div className="grid gap-4 md:grid-cols-2">{caseStudies.map(item => <Card key={item.id} className={`border-0 shadow-sm ring-1 ${item.unlocked ? 'bg-white ring-slate-200' : 'bg-slate-50 ring-slate-200/60'}`}><CardContent className="p-6"><div className="flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-2xl ${item.unlocked ? 'bg-indigo-50 text-indigo-600' : 'bg-slate-100 text-slate-400'}`}>{item.status === 'completed' ? <CheckCircle2 /> : item.unlocked ? <FlaskConical /> : <LockKeyhole />}</span><Badge variant="outline" className="capitalize">{item.status.replace('_', ' ')}</Badge></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-indigo-600">Case study {item.number}</p><h2 className="mt-1 text-xl font-bold">{item.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.scenario}</p><div className="mt-4 flex flex-wrap gap-2">{item.objectives.slice(0, 2).map(o => <span key={o} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{o}</span>)}</div>{item.unlocked && <Button asChild className="mt-5 w-full"><Link href={`/case-studies/${item.id}`}>Open project</Link></Button>}</CardContent></Card>)}</div></div></main></>;
}
CaseStudies.layout = { breadcrumbs: [{ title: 'Case Studies', href: '/case-studies' }] };
