import { Form, Head, Link, router, usePage, usePoll } from '@inertiajs/react';
import { Copy, KeyRound, Plus, Search, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Student = { id: number; name: string; username: string; grade: string; section: string; status: string; completed: number; awaitingReview: number; progress: number; lastLogin: string };
type Credentials = { name: string; username: string; password: string };
type Props = { students: { data: Student[] }; filters: { search?: string } };

export default function Students({ students, filters }: Props) {
    usePoll(15000, { only: ['students'] });
    const page = usePage();
    const credentials = (page.props.flash as { credentials?: Credentials } | undefined)?.credentials;
    const [credentialOpen, setCredentialOpen] = useState(Boolean(credentials));
    useEffect(() => { if (credentials) setCredentialOpen(true); }, [credentials]);
    const copy = (text: string) => navigator.clipboard.writeText(text);
    return <><Head title="Students" /><main className="soft-grid min-h-full p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
        <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge variant="outline">Teacher tools</Badge><h1 className="mt-3 text-3xl font-bold">Students</h1><p className="mt-2 text-muted-foreground">Create accounts and monitor individual learning progress.</p></div><Dialog><DialogTrigger asChild><Button><Plus /> Add student</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create student account</DialogTitle><DialogDescription>A secure temporary password will be generated once.</DialogDescription></DialogHeader><Form action="/students" method="post" className="grid gap-4 sm:grid-cols-2"><div><Label>First name</Label><Input name="first_name" required /></div><div><Label>Middle name</Label><Input name="middle_name" /></div><div><Label>Last name</Label><Input name="last_name" required /></div><div><Label>LRN (optional)</Label><Input name="lrn" /></div><div><Label>Grade level</Label><Input name="grade_level" required /></div><div><Label>Section</Label><Input name="section" required /></div><Button type="submit" className="sm:col-span-2">Create account</Button></Form></DialogContent></Dialog></header>
        <Card className="border-0 bg-white shadow-sm ring-1 ring-slate-200"><CardHeader><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 size-5 text-muted-foreground" /><Input defaultValue={filters.search} placeholder="Search name or username" className="pl-10" onChange={(e) => router.get('/students', { search: e.target.value }, { preserveState: true, replace: true })} /></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Student</th><th>Class</th><th>Progress</th><th>Completed</th><th>Needs review</th><th>Last login</th><th>Status</th><th /></tr></thead><tbody>{students.data.map(student => <tr key={student.id} className="border-b last:border-0"><td className="py-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-indigo-50 text-indigo-600"><UserRound className="size-5" /></span><div><p className="font-semibold">{student.name}</p><p className="text-xs text-muted-foreground">@{student.username}</p></div></div></td><td>{student.grade} · {student.section}</td><td><div className="flex items-center gap-2"><div className="h-2 w-24 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${student.progress}%` }} /></div>{student.progress}%</div></td><td>{student.completed}/15</td><td>{student.awaitingReview > 0 ? <Badge className="bg-amber-100 text-amber-900 hover:bg-amber-100">{student.awaitingReview} awaiting review</Badge> : <span className="text-muted-foreground">—</span>}</td><td className="text-muted-foreground">{student.lastLogin}</td><td><Badge variant={student.status === 'active' ? 'default' : 'secondary'}>{student.status}</Badge></td><td className="text-right"><Button asChild size="sm" variant="outline"><Link href={`/students/${student.id}`}>View</Link></Button></td></tr>)}</tbody></table></CardContent></Card>
    </div></main><Dialog open={credentialOpen} onOpenChange={setCredentialOpen}><DialogContent><DialogHeader><DialogTitle>Student Account Created</DialogTitle><DialogDescription>This password is shown only now. Copy or print it before closing.</DialogDescription></DialogHeader>{credentials && <div className="space-y-4"><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="font-semibold">{credentials.name}</p><div className="mt-4 grid grid-cols-[100px_1fr] gap-2 text-sm"><span className="text-slate-400">Username</span><code>{credentials.username}</code><span className="text-slate-400">Password</span><code className="text-amber-300">{credentials.password}</code></div></div><div className="grid gap-2 sm:grid-cols-2"><Button variant="outline" onClick={() => copy(credentials.username)}><Copy /> Copy username</Button><Button variant="outline" onClick={() => copy(credentials.password)}><KeyRound /> Copy password</Button><Button className="sm:col-span-2" onClick={() => copy(`Username: ${credentials.username}\nTemporary Password: ${credentials.password}`)}>Copy credentials</Button></div></div>}</DialogContent></Dialog></>;
}

Students.layout = { breadcrumbs: [{ title: 'Students', href: '/students' }] };
